# Site settings
title: jenkins-material-theme
email: me@afonsof.com
description: Beautify your Jenkins with the Material Design theme!
meta_title: Jenkins Theme - jenkins-material-theme
meta_description: Beautify your Jenkins with the Material Design theme! So you love Jenkins but hate its ugly user interface and iconsâ€¦ Me too! Introducing a Jenkins Theme based on Material Design. You can turn your favorite frog CI tool into a handsome prince in few steps!

baseurl: ""
url: "http://afonsof.github.io"
github_url: "https://github.com/afonsof/jenkins-material-theme"


# Build settings
markdown: kramdown

exclude: [node_modules, package.json, npm-debug.log, Gruntfile.js, scss, .tmp]
